// constants
export const GET_YESTERDAYS_GAMES_REQUEST = 'GET_YESTERDAYS_GAMES_REQUEST';
export const GET_YESTERDAYS_GAMES_RESPONSE = 'GET_YESTERDAYS_GAMES_RESPONSE';
export const GET_TODAYS_GAMES_REQUEST = 'GET_TODAYS_GAMES_REQUEST';
export const GET_TODAYS_GAMES_RESPONSE = 'GET_TODAYS_GAMES_RESPONSE';
export const GET_TOMORROWS_GAMES_REQUEST = 'GET_TOMORROWS_GAMES_REQUEST';
export const GET_TOMORROWS_GAMES_RESPONSE = 'GET_TOMORROWS_GAMES_RESPONSE';